[config]


[templates.kew]
input_path = "~/.config/noctalia/templates/noctalia.theme"
output_path = "~/.config/kew/themes/noctalia.theme"
post_hook = "kew theme noctalia"

[templates.rofi]
input_path = "~/.config/noctalia/templates/noctalia.rasi"
output_path = "~/.config/rofi/noctalia.rasi"
